### ISSUE TITLE
Databases + Travis

### ISSUE THREAD

**Issue by matthewdking** [fac-13/research#32]
So I have had problems with this in the past and struggled to find much in terms of documentation. There is a bit [here](https://docs.travis-ci.com/user/database-setup/).

I think essentially it comes down to adding this to your `travis.yml`
```yml
services:
  - postgresql
before_script:
  - psql -c 'create database nameOfDB;' -U postgres
```

Maybe writing another script to set env and build db? I have this script in one of my projects
```json
"pretest": "ENV=test npm run db-build",
```
